name: Automated Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
        
      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="dev-$(git rev-parse --short HEAD)"
          fi
          echo "Raw version from ref: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building BHTikTok++ version: $VERSION"
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
          
      - name: Accept Xcode License
        run: sudo xcodebuild -license accept
        
      - name: Install Theos
        run: |
          echo "Installing Theos..."
          # Install Theos to /opt/theos instead of default location
          sudo mkdir -p /opt/theos
          sudo chown -R $(whoami) /opt/theos
          
          # Clone Theos manually for more control
          git clone --recursive https://github.com/theos/theos.git /opt/theos
          
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
          
          # Install required dependencies
          brew install ldid xz
          
      - name: Install iOS SDK
        run: |
          echo "Installing iOS SDK..."
          mkdir -p /opt/theos/sdks
          cd /opt/theos/sdks
          
          # Download iOS 16.5 SDK
          echo "Downloading iOS 16.5 SDK..."
          curl -L -o iPhoneOS16.5.sdk.tar.xz https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz
          
          # Extract the SDK
          echo "Extracting iOS SDK..."
          tar -xf iPhoneOS16.5.sdk.tar.xz
          
          # Clean up the archive
          rm iPhoneOS16.5.sdk.tar.xz
          
          # Verify SDK installation
          echo "Installed SDKs:"
          ls -la /opt/theos/sdks/
          
      - name: Verify Theos Installation
        run: |
          echo "Verifying Theos installation..."
          echo "THEOS path: $THEOS"
          echo "Theos directory contents:"
          ls -la $THEOS/
          echo "Available iOS SDKs:"
          ls -la $THEOS/sdks/
          echo "Makefiles directory:"
          ls -la $THEOS/makefiles/ | head -10
          
      - name: Update version in control file
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          # Remove 'v' prefix if present for control file
          CLEAN_VERSION=${VERSION#v}
          echo "Updating control file with version: $CLEAN_VERSION"
          sed -i.bak "s/^Version:.*/Version: $CLEAN_VERSION/" control
          cat control
          
      - name: Clean and build tweak
        run: |
          echo "Building BHTikTok++ tweak..."
          export THEOS=/opt/theos
          
          # Build release version (optimized, stripped)
          echo "Building release package..."
          make clean
          make package FINALPACKAGE=1
          
          # Move release package to safe location
          mkdir -p build-artifacts
          if ls packages/*.deb 1> /dev/null 2>&1; then
            # Find and copy the release package
            RELEASE_PKG=$(find packages -name "*.deb" -type f | head -1)
            cp "$RELEASE_PKG" build-artifacts/release.deb
            echo "Release package saved as build-artifacts/release.deb"
            ls -la "$RELEASE_PKG"
          fi

          # Clear packages directory before debug build
          rm -rf packages
          mkdir -p packages

          # Build debug version (with debug symbols)
          echo "Building debug package..."
          make clean
          make package DEBUG=1
          
          # Move debug package to safe location
          if ls packages/*.deb 1> /dev/null 2>&1; then
            # Find and copy the debug package
            DEBUG_PKG=$(find packages -name "*.deb" -type f | head -1)
            cp "$DEBUG_PKG" build-artifacts/debug.deb
            echo "Debug package saved as build-artifacts/debug.deb"
            ls -la "$DEBUG_PKG"
          fi
          
          # Clear packages directory and restore both packages with clear names
          rm -rf packages
          mkdir -p packages
          if [[ -f "build-artifacts/release.deb" ]]; then
            cp build-artifacts/release.deb packages/release.deb
            echo "Restored release package to packages/release.deb"
          fi
          if [[ -f "build-artifacts/debug.deb" ]]; then
            cp build-artifacts/debug.deb packages/debug.deb
            echo "Restored debug package to packages/debug.deb"
          fi
          
      - name: List build artifacts
        run: |
          echo "Build completed. Listing artifacts..."
          find . -name "*.deb" -type f
          ls -la packages/ || echo "No packages directory found"
          
      - name: Prepare release assets
        id: prepare_assets
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          # Clean version string - remove 'v' prefix and any leading dots
          CLEAN_VERSION=${VERSION#v}
          CLEAN_VERSION=${CLEAN_VERSION#.}
          
          echo "Original version: $VERSION"
          echo "Cleaned version: $CLEAN_VERSION"
          
          # Find the generated .deb files
          echo "Looking for .deb files..."
          find packages -name "*.deb" -type f | sort
          
          # Check for our specifically named files
          RELEASE_DEB_FILE=""
          DEBUG_DEB_FILE=""
          
          if [[ -f "packages/release.deb" ]]; then
            RELEASE_DEB_FILE="packages/release.deb"
            echo "Found release package: $RELEASE_DEB_FILE"
          fi
          
          if [[ -f "packages/debug.deb" ]]; then
            DEBUG_DEB_FILE="packages/debug.deb"
            echo "Found debug package: $DEBUG_DEB_FILE"
          fi
          
          # If we don't have our named files, fall back to discovery
          if [[ -z "$RELEASE_DEB_FILE" ]]; then
            DEB_FILES=($(find packages -name "*.deb" -type f | sort))
            if [[ ${#DEB_FILES[@]} -gt 0 ]]; then
              RELEASE_DEB_FILE="${DEB_FILES[0]}"
              echo "Using fallback release package: $RELEASE_DEB_FILE"
            fi
          fi
          
          if [[ -z "$RELEASE_DEB_FILE" ]]; then
            echo "ERROR: No .deb files found!"
            exit 1
          fi
          
          # Rename release package
          if [[ -f "$RELEASE_DEB_FILE" ]]; then
            RELEASE_DEB_NAME="BHTikTok++-${CLEAN_VERSION}.deb"
            cp "$RELEASE_DEB_FILE" "$RELEASE_DEB_NAME"
            echo "RELEASE_DEB_FILE=$RELEASE_DEB_NAME" >> $GITHUB_OUTPUT
            echo "Found and renamed release .deb file: $RELEASE_DEB_NAME"
            ls -la "$RELEASE_DEB_NAME"
          fi
          
          # Rename debug package if it exists
          if [[ -n "$DEBUG_DEB_FILE" && -f "$DEBUG_DEB_FILE" ]]; then
            DEBUG_DEB_NAME="BHTikTok++-${CLEAN_VERSION}-debug.deb"
            cp "$DEBUG_DEB_FILE" "$DEBUG_DEB_NAME"
            echo "DEBUG_DEB_FILE=$DEBUG_DEB_NAME" >> $GITHUB_OUTPUT
            echo "Found and renamed debug .deb file: $DEBUG_DEB_NAME"
            ls -la "$DEBUG_DEB_NAME"
          fi
          
      - name: Generate changelog
        id: changelog
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "Generating changelog for version $VERSION"
          
          # Try to get changelog from tag message or recent commits
          if git tag -l --format='%(contents)' "$VERSION" | head -1 | grep -q .; then
            CHANGELOG=$(git tag -l --format='%(contents)' "$VERSION")
          else
            echo "## Changes in $VERSION" > changelog.md
            echo "" >> changelog.md
            
            # Get commits since last tag
            PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
            if [[ -n "$PREV_TAG" ]]; then
              echo "### Commits since $PREV_TAG:" >> changelog.md
              git log --pretty=format:"- %s (%h)" "$PREV_TAG..HEAD" >> changelog.md
            else
              echo "### Recent commits:" >> changelog.md
              git log --pretty=format:"- %s (%h)" -10 >> changelog.md
            fi
            
            CHANGELOG=$(cat changelog.md)
          fi
          
          # Save changelog to file for release notes
          echo "$CHANGELOG" > release_notes.md
          echo "Generated changelog:"
          cat release_notes.md
          
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.prepare_assets.outputs.RELEASE_DEB_FILE }}
            ${{ steps.prepare_assets.outputs.DEBUG_DEB_FILE }}
          body_path: release_notes.md
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BHTikTok++-${{ steps.get_version.outputs.VERSION }}
          path: |
            ${{ steps.prepare_assets.outputs.RELEASE_DEB_FILE }}
            ${{ steps.prepare_assets.outputs.DEBUG_DEB_FILE }}
            release_notes.md
          retention-days: 30
          
      - name: Build summary
        run: |
          echo "## ✅ BHTikTok++ Release Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "**Release Package:** ${{ steps.prepare_assets.outputs.RELEASE_DEB_FILE }}" >> $GITHUB_STEP_SUMMARY
          if [[ -n "${{ steps.prepare_assets.outputs.DEBUG_DEB_FILE }}" ]]; then
            echo "**Debug Package:** ${{ steps.prepare_assets.outputs.DEBUG_DEB_FILE }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "**Release Package:** ${{ steps.prepare_assets.outputs.RELEASE_DEB_FILE }}" >> $GITHUB_STEP_SUMMARY
          if [[ -n "${{ steps.prepare_assets.outputs.DEBUG_DEB_FILE }}" ]]; then
            echo "**Debug Package:** ${{ steps.prepare_assets.outputs.DEBUG_DEB_FILE }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Release Assets:" >> $GITHUB_STEP_SUMMARY
          echo "- **Release .deb**: Optimized package for production use (stripped symbols)" >> $GITHUB_STEP_SUMMARY
          if [[ -n "${{ steps.prepare_assets.outputs.DEBUG_DEB_FILE }}" ]]; then
            echo "- **Debug .deb**: Development package with debug symbols for troubleshooting" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- **Source Code**: Available as GitHub's automatic zip/tar.gz downloads" >> $GITHUB_STEP_SUMMARY
          echo "- **Automated Changelog**: Generated from git history and tag annotations" >> $GITHUB_STEP_SUMMARY
